[build]
  command = "npm run build"
  publish = ".next"
  base = "/"

[build.environment]
  NEXT_PUBLIC_BASE_URL = "https://lagosautopvd.netlify.app"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 